### PR TITLE
remove obsolete

### PR DESCRIPTION
**Pull request by gbiellem**
@mikeminutillo  since the code signing is bumping the version to 3 we need to deal with the obsolete PeriodicCheck.  Are you happy to have this removed?

### CODE REVIEW

**Comment by mikeminutillo** [comment]
This is part of the versioning hell with these plugins. Ideally, this stuff would get removed in the next Core major which is when I expect people to be updating them. Anyone updating from the Core V6 to Core V6 versions of these plugins will not have these obsoletes to guide them on what we changed.

**Comment by gbiellem** [comment]
@mikeminutillo  so undo and bump the version on the obsolete?

**Comment by mikeminutillo** [comment]
Yeah I think so.

**Comment by gbiellem** [comment]
Cool. Will do

**Pull request closed without merging**
